# -*- coding: utf-8 -*-
"""print_num.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1czvz2j2MhUsKUI0b_eyYXRpxZwrQpeDm

**عدد چاپ کن**

برنامه‌ای بنويسيد كه یک عدد صحيح را که تعداد ارقامش مشخص نيست از کاربر گرفته و 
هر رقم را به تعداد آن رقم چاپ کند.
ورودی

در یک خط عدد به شما داده می‌شود. طول عدد از ۱۰۰ کوچکتر است
خروجی

به ازای هر رقم ابتدا خود آن رقم به همراه ‍: را چاپ کرده سپس به تعداد آن رقم از همان رقم چاپ کنید.
"""

num=input('please enter number below 100')
print(num,':',str(num) * int(num))







